services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Programacion42026"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__devConnection: "Server=db;Database=CursosDB;User Id=sa;Password=Programacion42026;TrustServerCertificate=True;"
volumes:
  sqlserverdata: